### ISSUE TITLE
add ability to add change before commiting  

### ISSUE THREAD

**Issue by veritem** [veritem/gcommit#3]
basically don't always panic when there is unstaged changes

**Comment by regisrex** [comment]
Possible if we automatically  execute `git add .` which  kinda sucks :lol

**Comment by regisrex** [comment]
> Possible if we automatically execute `git add .` which kinda sucks :lol

but we can first ask the user if we should add all changes or quit gcommit  add let them add the changes using the normal way.

**Comment by veritem** [comment]
I implemented this incase you didn't know
