### ISSUE TITLE
installation script

### ISSUE THREAD

**Issue by veritem** [veritem/gcommit#7]

**Comment by veritem** [comment]
decided to use cargo install for now. To install do `cargo install gcommit`

**Comment by regisrex** [comment]
Been walking around and found something  that you might have used to build  other versions.
https://github.com/veritem/homebrew-gcm/blob/main/Formula/gcm.rb

I'm tryna see if it can help with sthi.

**Comment by veritem** [comment]
I don't know if i want to use homebrew because it works only on macos.

**Comment by veritem** [comment]
got it working without arm64 (apple silicon chips) architecture support. need more people to try it. 

```bash
curl -fsSL https://light-bison-49.deno.dev/ | sh 
```
